name: neutron-proxy
services:
  - dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: dalihsusilo/neutron-proxy
    name: neutron-proxy
    internal_ports:
      - 8080
