name: neutron-proxy
region: nyc
services:
  - dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: dalihsusilo/neutron-proxy
    name: neutron-proxy
    http_port: 3128
    routes:
      - /
